### ISSUE TITLE
Code for mutual information test?

### ISSUE THREAD

**Issue by ianbstewart** [jxhe/vae-lagging-encoder#1]
Hello,

Thanks for putting up this code! I was curious to know what part of the code you used to generate the mutual information plots shown in Figure 5 of the paper. Can you point me to that?

**Comment by jxhe** [comment]
Sure, thanks for your interest. Mutual information is calculated [here](https://github.com/jxhe/vae-lagging-encoder/blob/a3613a2e7781760bc7893dbb01fca7cef97afa9c/modules/encoders/encoder.py#L138), this function is called [here](https://github.com/jxhe/vae-lagging-encoder/blob/a3613a2e7781760bc7893dbb01fca7cef97afa9c/text.py#L157).

**Comment by ianbstewart** [comment]
Thanks for the reply. I figured out how to compute MI already, but I was wondering where specifically you generated Figure 5. I was trying to replicate the figure using my own data and had trouble doing that.

**Comment by jxhe** [comment]
To create Figure 5, I first ran the code and post-processed the standard output to plot. I just pushed the plotting notebook, see [here](https://github.com/jxhe/vae-lagging-encoder/blob/master/plot_notebook/plot_log.ipynb) for an example to read output log and create Figure 5.

**Comment by ianbstewart** [comment]
Thanks for the notebook. I assume the output log is generated by another class/file?

**Comment by jxhe** [comment]
Sorry there is no specific class/file for logging. I just redirected standard output to a file.

**Comment by ianbstewart** [comment]
That's OK. In what file/class is the standard output generated?

**Comment by jxhe** [comment]
The logs are printed out to `stdout` in `text.py` and `image.py`
