### ISSUE TITLE
Code for computing true posterior

### ISSUE THREAD

**Issue by valdersoul** [jxhe/vae-lagging-encoder#2]
Hi,

In the paper, it says that the true posterior can be computed by sum(z*p(z|x) in Appendix A. However, in the code it seems that it is calculating the likelihood P(z,x)? Why?

**Comment by jxhe** [comment]
Note that p(z|x) \propto p(z, x) and we did the normalization for p(z, x)([here](https://github.com/jxhe/vae-lagging-encoder/blob/91af04a1cb36bf2e20a251fd4286b3417877de31/modules/vae.py#L174)), so the returned tensor is actually posterior p(z|x)

**Comment by jxhe** [comment]
Sorry I realized the Figures on synthetic data (and the posterior mean calculation) is generated by a different branch, and the master branch is not updated to computer the posterior mean. I will update master to include the posterior mean calculation. Thanks for pointing this out !

**Comment by jxhe** [comment]
I have moved the posterior computation components to master branch from synthetic-plot branch, please refer [here](https://github.com/jxhe/vae-lagging-encoder/blob/e4980e674889546d925c56d74006f230ec9a0fb7/modules/vae.py#L140) for computation of p(z|x)

**Comment by valdersoul** [comment]
Thanks for your reply and fix!
