### ISSUE TITLE
generating/sampling sentences

### ISSUE THREAD

**Issue by sb1992** [jxhe/vae-lagging-encoder#4]
I was wondering if you have a script for sampling or generating sentences. I can see there is a function sample_sentences in text.py but am not able to run it properly. Can you help me out in using that function to generate sentences so that i can see some samples?

Thanks

**Comment by jxhe** [comment]
Yes I have implementations for reconstruction/sampling. I will push them and include usage instructions today or tomorrow ;)

**Comment by sb1992** [comment]
Thanks, I also had a question about batch size. Do you reckon changing batch size will have significant impact ?

**Comment by jxhe** [comment]
1. Sorry I don't know -- I didn't experiment with different batch size before. 

2. I just added sentence generation supports to this repo, please see README for usage instructions ;)

**Comment by sb1992** [comment]
Thank you
