### ISSUE TITLE
Training time for text data

### ISSUE THREAD

**Issue by yannadani** [jxhe/vae-lagging-encoder#7]
Hi,

Thanks for the code and a very nice work! I was trying to run your code on yahoo dataset on GPU and it seems to be taking longer than what is reported in the paper. In the paper, it is reported 11 hours, but I have been running for 2 days and it is still in epoch 3. Am I doing something wrong? Any information on this would be great.

**Comment by jxhe** [comment]
I just cloned this repo yesterday and reran the experiments on Yahoo with:

`CUDA_VISIBLE_DEVICES=0 python text.py --dataset yahoo --aggressive 1 --warm_up 10 --kl_start 0.1`

It costs like 14 hours to finish, I was using NVIDIA GTX 1080 Ti, what GPU card did you use ?

I would suggest you to 1. check to make sure the program is indeed using GPU -- if it uses GPU, then the first line of the log file should be `using cuda` 2. make sure only this program is running under that GPU device -- multiple programs using the same device would slow down each other. 3. check the GPU card version

**Comment by yannadani** [comment]
Hi, pulled the latest master and tried again and it now works as expected. Thanks a lot for the help!
