### ISSUE TITLE
Does a vanilla VAE show PC for text model?

### ISSUE THREAD

**Issue by yannadani** [jxhe/vae-lagging-encoder#8]
Hi,

From your experiments, does a vanilla VAE show posterior collapse for say yahoo dataset? I ran with 
`python text.py --dataset yahoo --kl_start 1.0` and found that KL term remains non zero while MI and AU go to zero (In fact MI is negative). Is this the expected behaviour ?

**Comment by jxhe** [comment]
In my experiments a vanilla VAE shows posterior collapse for the yahoo dataset. What's the scale of your non zero KL term ? Can you share the running log ?

**Comment by yannadani** [comment]
Hello, 
I had made a slight error when running it. The KL term is indeed very small. But I would like to know if MI going negative the right thing? Should it not be always non-negative?

Thanks for your response.

**Comment by jxhe** [comment]
MI should be always non-negative, but the approximation to MI has some variance. When MI is very small the variance might produce negative approximation, but I believe the "negative MI" number should be close to zero.
