### ISSUE TITLE
Evaluation of beta vae model in the paper

### ISSUE THREAD

**Issue by sbharadwajj** [jxhe/vae-lagging-encoder#9]
Hello, 
Thanks for the code. I was wondering what is the value of beta to be used during testing for the baseline beta vae models in your paper. Is it always one or the fixed beta? 

Also, in case of VAE + annealing, how is the model selection during training done? By evaluating NLL on current value of beta or beta=1? 

Thanks

**Comment by jxhe** [comment]
Hi,

For both beta VAE and annealing VAE, I always use beta=1 for validation and testing.
